name: "Hello Actions"
description: "Great someone"
author: "octocat@github.com"

inputs:
        MY_NAME:
                description: "Who to greet"
                required: true
                default: "World"

runs:
        using: "docker"
        image: "Dockerfile"

brading:
        icon: "mic"
        color: "purple"
